# Generated by Django 4.2.30 on 2026-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionbatch_and_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credited_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
