# Generated by Django 4.2.30 on 2026-05-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_credited_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
