# Generated by Django 4.2.30 on 2026-05-06 11:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_partition_transactions_by_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftTransferDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swift_code', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='SWIFT code must contain 8 or 11 uppercase letters and digits.', regex='^[A-Z0-9]{8}([A-Z0-9]{3})?$')])),
                ('beneficiary_name', models.CharField(db_index=True, max_length=255)),
                ('beneficiary_account_number', models.CharField(max_length=34)),
                ('beneficiary_iban', models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator(message='IBAN must contain 15 to 34 uppercase letters and digits.', regex='^[A-Z0-9]{15,34}$')])),
                ('beneficiary_bank_name', models.CharField(db_index=True, max_length=255)),
                ('beneficiary_bank_country', models.CharField(db_index=True, max_length=2, validators=[django.core.validators.RegexValidator(message='Bank country must be a 2-letter ISO country code.', regex='^[A-Z]{2}$')])),
                ('beneficiary_address', models.TextField(blank=True)),
                ('swift_reference', models.CharField(blank=True, db_index=True, max_length=64)),
                ('scheduled_processing_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expected_completion_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('swift_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=18)),
                ('swift_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0100'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='swift_details', to='transactions.transaction')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='swifttransferdetails',
            constraint=models.CheckConstraint(check=models.Q(('swift_fee_fixed__gte', Decimal('0.00'))), name='swift_details_fee_fixed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='swifttransferdetails',
            constraint=models.CheckConstraint(check=models.Q(('swift_fee_rate__gte', Decimal('0.0000'))), name='swift_details_fee_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='swifttransferdetails',
            constraint=models.CheckConstraint(check=models.Q(('swift_fee_rate__lte', Decimal('1.0000'))), name='swift_details_fee_rate_lte_one'),
        ),
    ]
