# Generated by Django 4.2.30 on 2026-05-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_system_and_more'),
        ('transactions', '0011_swifttransferdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('swift', 'Swift')], db_index=True, default='internal', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('to_account__isnull', True), ('transfer_type', 'internal'), _negated=True), name='txn_internal_requires_to_account'),
        ),
    ]
