# Generated by Django 4.2.30 on 2026-05-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0012_transaction_transfer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('transaction_attempt', 'Transaction attempt'), ('login', 'Login'), ('challenge', 'Challenge'), ('blocked', 'Blocked')], db_index=True, max_length=32)),
                ('outcome', models.CharField(choices=[('allowed', 'Allowed'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], db_index=True, max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_events', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', 'created_at'], name='fraud_evt_user_created_idx'), models.Index(fields=['user', 'event_type', 'created_at'], name='fraud_evt_user_type_idx'), models.Index(fields=['user', 'outcome', 'created_at'], name='fraud_evt_user_outcome_idx')],
            },
        ),
    ]
