# Generated by Django 4.2.30 on 2026-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], db_index=True, max_length=3)),
                ('quote_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], db_index=True, max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('provider', models.CharField(db_index=True, default='manual', max_length=50)),
                ('fetched_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'provider'), name='unique_exchange_rate_per_provider_pair'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(('base_currency', models.F('quote_currency')), _negated=True), name='exchange_rate_currencies_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(check=models.Q(('rate__gt', 0)), name='exchange_rate_must_be_positive'),
        ),
    ]
